[package]
name = "rustier-simplicity"
version = "0.1.0"
edition = "2021"
description = "Implementation of Simplicity using Rust's type system"
authors = ["Christian Lewe"]

[dependencies]
thiserror = "1.0.40"
